[tools]

# Cloud CLI
gcloud = "latest"

# Kube
kubectl = "1.34"
krew = "0.4"
terraform = "1.13"

# Data Parsing
yq = "4"
jq = "latest"

# Build Tools
just = "1"

# Git
pre-commit = "4"

[hooks]
postinstall = "kubectl krew install ctx -v0"
