[tools]

# Cloud CLI
gcloud = "latest"

# Kube
helm = "latest"
krew = "0.4"
kubectl = "1.34"

# IaC
terraform = "1.13"

# Data Parsing
jq = "latest"
yq = "4"

# Build Tools
just = "1"

# Git
pre-commit = "4"

[hooks]
postinstall = "kubectl krew install ctx -v0; gcloud components install --quiet gke-gcloud-auth-plugin"
